version: "3.8"
services:
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build: ./Server
    env_file:
      - ./Server/.env
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL
